/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransacoesIndexRouteImport } from './routes/transacoes/index'
import { Route as TotaisIndexRouteImport } from './routes/totais/index'
import { Route as PessoasIndexRouteImport } from './routes/pessoas/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesIndexRoute = TransacoesIndexRouteImport.update({
  id: '/transacoes/',
  path: '/transacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TotaisIndexRoute = TotaisIndexRouteImport.update({
  id: '/totais/',
  path: '/totais/',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasIndexRoute = PessoasIndexRouteImport.update({
  id: '/pessoas/',
  path: '/pessoas/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pessoas/': typeof PessoasIndexRoute
  '/totais/': typeof TotaisIndexRoute
  '/transacoes/': typeof TransacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pessoas': typeof PessoasIndexRoute
  '/totais': typeof TotaisIndexRoute
  '/transacoes': typeof TransacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pessoas/': typeof PessoasIndexRoute
  '/totais/': typeof TotaisIndexRoute
  '/transacoes/': typeof TransacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pessoas/' | '/totais/' | '/transacoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pessoas' | '/totais' | '/transacoes'
  id: '__root__' | '/' | '/pessoas/' | '/totais/' | '/transacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PessoasIndexRoute: typeof PessoasIndexRoute
  TotaisIndexRoute: typeof TotaisIndexRoute
  TransacoesIndexRoute: typeof TransacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes/': {
      id: '/transacoes/'
      path: '/transacoes'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof TransacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totais/': {
      id: '/totais/'
      path: '/totais'
      fullPath: '/totais/'
      preLoaderRoute: typeof TotaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/': {
      id: '/pessoas/'
      path: '/pessoas'
      fullPath: '/pessoas/'
      preLoaderRoute: typeof PessoasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PessoasIndexRoute: PessoasIndexRoute,
  TotaisIndexRoute: TotaisIndexRoute,
  TransacoesIndexRoute: TransacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
